
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import org.datacontract.schemas._2004._07.ivps_ws.ArrayOfAlarmInfo;
import org.datacontract.schemas._2004._07.ivps_ws.ArrayOfCameraInfo;
import org.datacontract.schemas._2004._07.ivps_ws.ArrayOfReaFacelRecoInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWebService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.datacontract.schemas._2004._07.ivps.ObjectFactory.class,
    org.datacontract.schemas._2004._07.ivps_ws.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IWebService {


    /**
     * 
     * @param uid
     * @param pwd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/IWebService/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
    public String login(
        @WebParam(name = "uid", targetNamespace = "http://tempuri.org/")
        String uid,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param token
     * @return
     *     returns org.datacontract.schemas._2004._07.ivps_ws.ArrayOfCameraInfo
     */
    @WebMethod(operationName = "GetCameraList", action = "http://tempuri.org/IWebService/GetCameraList")
    @WebResult(name = "GetCameraListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCameraList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCameraList")
    @ResponseWrapper(localName = "GetCameraListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCameraListResponse")
    public ArrayOfCameraInfo getCameraList(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param month
     * @param year
     * @param cameraId
     * @param isDescOrder
     * @param end
     * @param eventType
     * @param keyword
     * @param day
     * @param begin
     * @param token
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetMediaHistoryDataCount", action = "http://tempuri.org/IWebService/GetMediaHistoryDataCount")
    @WebResult(name = "GetMediaHistoryDataCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMediaHistoryDataCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMediaHistoryDataCount")
    @ResponseWrapper(localName = "GetMediaHistoryDataCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMediaHistoryDataCountResponse")
    public int getMediaHistoryDataCount(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        int year,
        @WebParam(name = "month", targetNamespace = "http://tempuri.org/")
        int month,
        @WebParam(name = "day", targetNamespace = "http://tempuri.org/")
        int day,
        @WebParam(name = "isDescOrder", targetNamespace = "http://tempuri.org/")
        boolean isDescOrder,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "begin", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar begin,
        @WebParam(name = "end", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar end,
        @WebParam(name = "eventType", targetNamespace = "http://tempuri.org/")
        EventType eventType,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        String keyword);

    /**
     * 
     * @param month
     * @param year
     * @param pageIndex
     * @param cameraId
     * @param pageSize
     * @param isDescOrder
     * @param end
     * @param eventType
     * @param keyword
     * @param day
     * @param begin
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfMediaEventRecordInfo
     */
    @WebMethod(operationName = "GetMediaHistoryDataList", action = "http://tempuri.org/IWebService/GetMediaHistoryDataList")
    @WebResult(name = "GetMediaHistoryDataListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMediaHistoryDataList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMediaHistoryDataList")
    @ResponseWrapper(localName = "GetMediaHistoryDataListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMediaHistoryDataListResponse")
    public ArrayOfMediaEventRecordInfo getMediaHistoryDataList(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        int year,
        @WebParam(name = "month", targetNamespace = "http://tempuri.org/")
        int month,
        @WebParam(name = "day", targetNamespace = "http://tempuri.org/")
        int day,
        @WebParam(name = "PageSize", targetNamespace = "http://tempuri.org/")
        int pageSize,
        @WebParam(name = "PageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex,
        @WebParam(name = "isDescOrder", targetNamespace = "http://tempuri.org/")
        boolean isDescOrder,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "begin", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar begin,
        @WebParam(name = "end", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar end,
        @WebParam(name = "eventType", targetNamespace = "http://tempuri.org/")
        EventType eventType,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        String keyword);

    /**
     * 
     * @param month
     * @param year
     * @param cameraId
     * @param retTopNum
     * @param isDescOrder
     * @param end
     * @param eventType
     * @param keyword
     * @param day
     * @param begin
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfMediaEventRecordInfo
     */
    @WebMethod(operationName = "GetMediaHistoryDataListEx", action = "http://tempuri.org/IWebService/GetMediaHistoryDataListEx")
    @WebResult(name = "GetMediaHistoryDataListExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMediaHistoryDataListEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMediaHistoryDataListEx")
    @ResponseWrapper(localName = "GetMediaHistoryDataListExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMediaHistoryDataListExResponse")
    public ArrayOfMediaEventRecordInfo getMediaHistoryDataListEx(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        int year,
        @WebParam(name = "month", targetNamespace = "http://tempuri.org/")
        int month,
        @WebParam(name = "day", targetNamespace = "http://tempuri.org/")
        int day,
        @WebParam(name = "isDescOrder", targetNamespace = "http://tempuri.org/")
        boolean isDescOrder,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "begin", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar begin,
        @WebParam(name = "end", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar end,
        @WebParam(name = "eventType", targetNamespace = "http://tempuri.org/")
        EventType eventType,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        String keyword,
        @WebParam(name = "retTopNum", targetNamespace = "http://tempuri.org/")
        int retTopNum);

    /**
     * 
     * @param month
     * @param year
     * @param cameraId
     * @param retTopNum
     * @param personId
     * @param end
     * @param day
     * @param begin
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfMediaEventRecordInfo
     */
    @WebMethod(operationName = "GetMediaHistoryDataListPersonID", action = "http://tempuri.org/IWebService/GetMediaHistoryDataListPersonID")
    @WebResult(name = "GetMediaHistoryDataListPersonIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMediaHistoryDataListPersonID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMediaHistoryDataListPersonID")
    @ResponseWrapper(localName = "GetMediaHistoryDataListPersonIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMediaHistoryDataListPersonIDResponse")
    public ArrayOfMediaEventRecordInfo getMediaHistoryDataListPersonID(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId,
        @WebParam(name = "year", targetNamespace = "http://tempuri.org/")
        int year,
        @WebParam(name = "month", targetNamespace = "http://tempuri.org/")
        int month,
        @WebParam(name = "day", targetNamespace = "http://tempuri.org/")
        int day,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "begin", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar begin,
        @WebParam(name = "end", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar end,
        @WebParam(name = "retTopNum", targetNamespace = "http://tempuri.org/")
        int retTopNum);

    /**
     * 
     * @param filename
     * @param token
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetPicFileBytes", action = "http://tempuri.org/IWebService/GetPicFileBytes")
    @WebResult(name = "GetPicFileBytesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPicFileBytes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPicFileBytes")
    @ResponseWrapper(localName = "GetPicFileBytesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPicFileBytesResponse")
    public byte[] getPicFileBytes(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "filename", targetNamespace = "http://tempuri.org/")
        String filename);

    /**
     * 
     * @param filterIds
     * @param token
     * @return
     *     returns org.datacontract.schemas._2004._07.ivps_ws.ArrayOfAlarmInfo
     */
    @WebMethod(operationName = "GetRealAlarmList", action = "http://tempuri.org/IWebService/GetRealAlarmList")
    @WebResult(name = "GetRealAlarmListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRealAlarmList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRealAlarmList")
    @ResponseWrapper(localName = "GetRealAlarmListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRealAlarmListResponse")
    public ArrayOfAlarmInfo getRealAlarmList(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "filterIds", targetNamespace = "http://tempuri.org/")
        ArrayOfstring filterIds);

    /**
     * 
     * @param cameraId
     * @param filterIds
     * @param token
     * @return
     *     returns org.datacontract.schemas._2004._07.ivps_ws.ArrayOfReaFacelRecoInfo
     */
    @WebMethod(operationName = "GetReaFacelRecoInfoList", action = "http://tempuri.org/IWebService/GetReaFacelRecoInfoList")
    @WebResult(name = "GetReaFacelRecoInfoListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReaFacelRecoInfoList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReaFacelRecoInfoList")
    @ResponseWrapper(localName = "GetReaFacelRecoInfoListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReaFacelRecoInfoListResponse")
    public ArrayOfReaFacelRecoInfo getReaFacelRecoInfoList(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        Integer cameraId,
        @WebParam(name = "filterIds", targetNamespace = "http://tempuri.org/")
        ArrayOfint filterIds);

    /**
     * 
     * @param cameraId
     * @param time
     * @param jpegPicBytes
     * @param personType
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfUpFacePicRecoResult
     */
    @WebMethod(operationName = "UpFacePicReco", action = "http://tempuri.org/IWebService/UpFacePicReco")
    @WebResult(name = "UpFacePicRecoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpFacePicReco", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpFacePicReco")
    @ResponseWrapper(localName = "UpFacePicRecoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpFacePicRecoResponse")
    public ArrayOfUpFacePicRecoResult upFacePicReco(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "time", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar time,
        @WebParam(name = "jpegPicBytes", targetNamespace = "http://tempuri.org/")
        byte[] jpegPicBytes,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        PersonType personType);

    /**
     * 
     * @param personId
     * @param token
     * @return
     *     returns org.tempuri.PersonInfo
     */
    @WebMethod(operationName = "GetPersonInfo", action = "http://tempuri.org/IWebService/GetPersonInfo")
    @WebResult(name = "GetPersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonInfo")
    @ResponseWrapper(localName = "GetPersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonInfoResponse")
    public PersonInfo getPersonInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId);

    /**
     * 
     * @param personType
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfPersonInfo
     */
    @WebMethod(operationName = "GetAllPersonInfoListByPersonType", action = "http://tempuri.org/IWebService/GetAllPersonInfoListByPersonType")
    @WebResult(name = "GetAllPersonInfoListByPersonTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllPersonInfoListByPersonType", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPersonInfoListByPersonType")
    @ResponseWrapper(localName = "GetAllPersonInfoListByPersonTypeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAllPersonInfoListByPersonTypeResponse")
    public ArrayOfPersonInfo getAllPersonInfoListByPersonType(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        PersonType personType);

    /**
     * 
     * @param pageIndex
     * @param pageSize
     * @param personType
     * @param keyword
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfPersonInfo
     */
    @WebMethod(operationName = "GetPersonListByPage", action = "http://tempuri.org/IWebService/GetPersonListByPage")
    @WebResult(name = "GetPersonListByPageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonListByPage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonListByPage")
    @ResponseWrapper(localName = "GetPersonListByPageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonListByPageResponse")
    public ArrayOfPersonInfo getPersonListByPage(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        PersonType personType,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        String keyword,
        @WebParam(name = "PageSize", targetNamespace = "http://tempuri.org/")
        int pageSize,
        @WebParam(name = "PageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex);

    /**
     * 
     * @param pageIndex
     * @param pageSize
     * @param personType
     * @param keyword
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfPersonInfo
     */
    @WebMethod(operationName = "GetPersonListByPageEx", action = "http://tempuri.org/IWebService/GetPersonListByPageEx")
    @WebResult(name = "GetPersonListByPageExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonListByPageEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonListByPageEx")
    @ResponseWrapper(localName = "GetPersonListByPageExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonListByPageExResponse")
    public ArrayOfPersonInfo getPersonListByPageEx(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        int personType,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        String keyword,
        @WebParam(name = "PageSize", targetNamespace = "http://tempuri.org/")
        int pageSize,
        @WebParam(name = "PageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex);

    /**
     * 
     * @param pageIndex
     * @param pageSize
     * @param personType
     * @param keyword
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPersonListXmlByPage", action = "http://tempuri.org/IWebService/GetPersonListXmlByPage")
    @WebResult(name = "GetPersonListXmlByPageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonListXmlByPage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonListXmlByPage")
    @ResponseWrapper(localName = "GetPersonListXmlByPageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonListXmlByPageResponse")
    public String getPersonListXmlByPage(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        int personType,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        String keyword,
        @WebParam(name = "PageSize", targetNamespace = "http://tempuri.org/")
        int pageSize,
        @WebParam(name = "PageIndex", targetNamespace = "http://tempuri.org/")
        int pageIndex);

    /**
     * 
     * @param personType
     * @param keyword
     * @param token
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetPersonCount", action = "http://tempuri.org/IWebService/GetPersonCount")
    @WebResult(name = "GetPersonCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonCount")
    @ResponseWrapper(localName = "GetPersonCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonCountResponse")
    public int getPersonCount(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        PersonType personType,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        String keyword);

    /**
     * 
     * @param personType
     * @param keyword
     * @param token
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetPersonCountEx", action = "http://tempuri.org/IWebService/GetPersonCountEx")
    @WebResult(name = "GetPersonCountExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonCountEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonCountEx")
    @ResponseWrapper(localName = "GetPersonCountExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonCountExResponse")
    public int getPersonCountEx(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        int personType,
        @WebParam(name = "keyword", targetNamespace = "http://tempuri.org/")
        String keyword);

    /**
     * 
     * @param personInfo
     * @param token
     * @return
     *     returns long
     */
    @WebMethod(operationName = "AddPersonInfo", action = "http://tempuri.org/IWebService/AddPersonInfo")
    @WebResult(name = "AddPersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddPersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPersonInfo")
    @ResponseWrapper(localName = "AddPersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPersonInfoResponse")
    public long addPersonInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personInfo", targetNamespace = "http://tempuri.org/")
        PersonInfo personInfo);

    /**
     * 
     * @param startTime
     * @param stopTime
     * @param createPersonID
     * @param personInfo
     * @param token
     * @return
     *     returns long
     */
    @WebMethod(operationName = "StoreVisitorPersonInfo", action = "http://tempuri.org/IWebService/StoreVisitorPersonInfo")
    @WebResult(name = "StoreVisitorPersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StoreVisitorPersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StoreVisitorPersonInfo")
    @ResponseWrapper(localName = "StoreVisitorPersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StoreVisitorPersonInfoResponse")
    public long storeVisitorPersonInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "createPersonID", targetNamespace = "http://tempuri.org/")
        long createPersonID,
        @WebParam(name = "personInfo", targetNamespace = "http://tempuri.org/")
        PersonInfo personInfo,
        @WebParam(name = "startTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar startTime,
        @WebParam(name = "stopTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar stopTime);

    /**
     * 
     * @param personId
     * @param token
     * @return
     *     returns org.tempuri.VisitorInfo
     */
    @WebMethod(operationName = "GetVisitorInfo", action = "http://tempuri.org/IWebService/GetVisitorInfo")
    @WebResult(name = "GetVisitorInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVisitorInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVisitorInfo")
    @ResponseWrapper(localName = "GetVisitorInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVisitorInfoResponse")
    public VisitorInfo getVisitorInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId);

    /**
     * 
     * @param personId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RemoveVisitorPersonInfo", action = "http://tempuri.org/IWebService/RemoveVisitorPersonInfo")
    @WebResult(name = "RemoveVisitorPersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RemoveVisitorPersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveVisitorPersonInfo")
    @ResponseWrapper(localName = "RemoveVisitorPersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemoveVisitorPersonInfoResponse")
    public boolean removeVisitorPersonInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId);

    /**
     * 
     * @param personInfo
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UpdatePersonInfo", action = "http://tempuri.org/IWebService/UpdatePersonInfo")
    @WebResult(name = "UpdatePersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdatePersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePersonInfo")
    @ResponseWrapper(localName = "UpdatePersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdatePersonInfoResponse")
    public boolean updatePersonInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personInfo", targetNamespace = "http://tempuri.org/")
        PersonInfo personInfo);

    /**
     * 
     * @param personName
     * @param ext
     * @param sex
     * @param faceJpegBytes
     * @param idc
     * @param personType
     * @param token
     * @return
     *     returns long
     */
    @WebMethod(operationName = "AddPersonInfoEx", action = "http://tempuri.org/IWebService/AddPersonInfoEx")
    @WebResult(name = "AddPersonInfoExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddPersonInfoEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPersonInfoEx")
    @ResponseWrapper(localName = "AddPersonInfoExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddPersonInfoExResponse")
    public long addPersonInfoEx(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        int personType,
        @WebParam(name = "personName", targetNamespace = "http://tempuri.org/")
        String personName,
        @WebParam(name = "idc", targetNamespace = "http://tempuri.org/")
        String idc,
        @WebParam(name = "sex", targetNamespace = "http://tempuri.org/")
        String sex,
        @WebParam(name = "ext", targetNamespace = "http://tempuri.org/")
        String ext,
        @WebParam(name = "faceJpegBytes", targetNamespace = "http://tempuri.org/")
        byte[] faceJpegBytes);

    /**
     * 
     * @param personId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RemovePersonInfo", action = "http://tempuri.org/IWebService/RemovePersonInfo")
    @WebResult(name = "RemovePersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RemovePersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemovePersonInfo")
    @ResponseWrapper(localName = "RemovePersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RemovePersonInfoResponse")
    public boolean removePersonInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId);

    /**
     * 
     * @param personId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ExistPersonInfo", action = "http://tempuri.org/IWebService/ExistPersonInfo")
    @WebResult(name = "ExistPersonInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ExistPersonInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExistPersonInfo")
    @ResponseWrapper(localName = "ExistPersonInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExistPersonInfoResponse")
    public boolean existPersonInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId);

    /**
     * 
     * @param jpegPicBytes
     * @param token
     * @return
     *     returns org.tempuri.FaceInfo
     */
    @WebMethod(operationName = "GetPicMaxFaceFeatrueInfo", action = "http://tempuri.org/IWebService/GetPicMaxFaceFeatrueInfo")
    @WebResult(name = "GetPicMaxFaceFeatrueInfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPicMaxFaceFeatrueInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPicMaxFaceFeatrueInfo")
    @ResponseWrapper(localName = "GetPicMaxFaceFeatrueInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPicMaxFaceFeatrueInfoResponse")
    public FaceInfo getPicMaxFaceFeatrueInfo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "jpegPicBytes", targetNamespace = "http://tempuri.org/")
        byte[] jpegPicBytes);

    /**
     * 
     * @param topNum
     * @param jpegPicBytes
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfSearchReturnPersonInfo
     */
    @WebMethod(operationName = "SearchPerson", action = "http://tempuri.org/IWebService/SearchPerson")
    @WebResult(name = "SearchPersonResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchPerson", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPerson")
    @ResponseWrapper(localName = "SearchPersonResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonResponse")
    public ArrayOfSearchReturnPersonInfo searchPerson(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "jpegPicBytes", targetNamespace = "http://tempuri.org/")
        byte[] jpegPicBytes,
        @WebParam(name = "topNum", targetNamespace = "http://tempuri.org/")
        int topNum);

    /**
     * 
     * @param topNum
     * @param faceFeatrueBytes
     * @param token
     * @return
     *     returns org.tempuri.ArrayOfSearchReturnPersonInfo
     */
    @WebMethod(operationName = "SearchPersonEx", action = "http://tempuri.org/IWebService/SearchPersonEx")
    @WebResult(name = "SearchPersonExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchPersonEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonEx")
    @ResponseWrapper(localName = "SearchPersonExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonExResponse")
    public ArrayOfSearchReturnPersonInfo searchPersonEx(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "faceFeatrueBytes", targetNamespace = "http://tempuri.org/")
        byte[] faceFeatrueBytes,
        @WebParam(name = "topNum", targetNamespace = "http://tempuri.org/")
        int topNum);

    /**
     * 
     * @param faceFeatrueBytes
     * @param personId
     * @param token
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SearchPersonByPersonId", action = "http://tempuri.org/IWebService/SearchPersonByPersonId")
    @WebResult(name = "SearchPersonByPersonIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchPersonByPersonId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonByPersonId")
    @ResponseWrapper(localName = "SearchPersonByPersonIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonByPersonIdResponse")
    public int searchPersonByPersonId(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId,
        @WebParam(name = "faceFeatrueBytes", targetNamespace = "http://tempuri.org/")
        byte[] faceFeatrueBytes);

    /**
     * 
     * @param faceFeatrueBytes
     * @param idNo
     * @param token
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SearchPersonByIDNo", action = "http://tempuri.org/IWebService/SearchPersonByIDNo")
    @WebResult(name = "SearchPersonByIDNoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchPersonByIDNo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonByIDNo")
    @ResponseWrapper(localName = "SearchPersonByIDNoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonByIDNoResponse")
    public int searchPersonByIDNo(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "IDNo", targetNamespace = "http://tempuri.org/")
        String idNo,
        @WebParam(name = "faceFeatrueBytes", targetNamespace = "http://tempuri.org/")
        byte[] faceFeatrueBytes);

    /**
     * 
     * @param cameraId
     * @param state
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ControlIO_Output", action = "http://tempuri.org/IWebService/ControlIO_Output")
    @WebResult(name = "ControlIO_OutputResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ControlIO_Output", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ControlIOOutput")
    @ResponseWrapper(localName = "ControlIO_OutputResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ControlIOOutputResponse")
    public boolean controlIOOutput(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "CameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "state", targetNamespace = "http://tempuri.org/")
        int state);

    /**
     * 
     * @param personId
     * @param token
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetPersonFirstFacePicBytes", action = "http://tempuri.org/IWebService/GetPersonFirstFacePicBytes")
    @WebResult(name = "GetPersonFirstFacePicBytesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonFirstFacePicBytes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonFirstFacePicBytes")
    @ResponseWrapper(localName = "GetPersonFirstFacePicBytesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonFirstFacePicBytesResponse")
    public byte[] getPersonFirstFacePicBytes(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId);

    /**
     * 
     * @param topNum
     * @param jpegPicBytes
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SearchPersonReturnJosn", action = "http://tempuri.org/IWebService/SearchPersonReturnJosn")
    @WebResult(name = "SearchPersonReturnJosnResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SearchPersonReturnJosn", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonReturnJosn")
    @ResponseWrapper(localName = "SearchPersonReturnJosnResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SearchPersonReturnJosnResponse")
    public String searchPersonReturnJosn(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "jpegPicBytes", targetNamespace = "http://tempuri.org/")
        byte[] jpegPicBytes,
        @WebParam(name = "topNum", targetNamespace = "http://tempuri.org/")
        Integer topNum);

    /**
     * 
     * @param cameraId
     * @param personId
     * @param personType
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "CheckPersonHasAuthorizationPolicyAuth", action = "http://tempuri.org/IWebService/CheckPersonHasAuthorizationPolicyAuth")
    @WebResult(name = "CheckPersonHasAuthorizationPolicyAuthResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckPersonHasAuthorizationPolicyAuth", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckPersonHasAuthorizationPolicyAuth")
    @ResponseWrapper(localName = "CheckPersonHasAuthorizationPolicyAuthResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckPersonHasAuthorizationPolicyAuthResponse")
    public boolean checkPersonHasAuthorizationPolicyAuth(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "personType", targetNamespace = "http://tempuri.org/")
        PersonType personType,
        @WebParam(name = "personId", targetNamespace = "http://tempuri.org/")
        long personId,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId);

    /**
     * 
     * @param dateTime
     * @param score
     * @param cardInfo
     * @param takeFaceBytes
     * @param cameraId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddIDCardAndFaceRecoRecordToDb", action = "http://tempuri.org/IWebService/AddIDCardAndFaceRecoRecordToDb")
    @WebResult(name = "AddIDCardAndFaceRecoRecordToDbResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddIDCardAndFaceRecoRecordToDb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddIDCardAndFaceRecoRecordToDb")
    @ResponseWrapper(localName = "AddIDCardAndFaceRecoRecordToDbResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddIDCardAndFaceRecoRecordToDbResponse")
    public boolean addIDCardAndFaceRecoRecordToDb(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTime,
        @WebParam(name = "cardInfo", targetNamespace = "http://tempuri.org/")
        IDCardInfo cardInfo,
        @WebParam(name = "takeFaceBytes", targetNamespace = "http://tempuri.org/")
        byte[] takeFaceBytes,
        @WebParam(name = "score", targetNamespace = "http://tempuri.org/")
        int score);

    /**
     * 
     * @param dateTime
     * @param score
     * @param takeFaceBytes
     * @param cameraId
     * @param personInfo
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddRecoScuessRecordToDb", action = "http://tempuri.org/IWebService/AddRecoScuessRecordToDb")
    @WebResult(name = "AddRecoScuessRecordToDbResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddRecoScuessRecordToDb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRecoScuessRecordToDb")
    @ResponseWrapper(localName = "AddRecoScuessRecordToDbResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRecoScuessRecordToDbResponse")
    public boolean addRecoScuessRecordToDb(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTime,
        @WebParam(name = "takeFaceBytes", targetNamespace = "http://tempuri.org/")
        byte[] takeFaceBytes,
        @WebParam(name = "personInfo", targetNamespace = "http://tempuri.org/")
        PersonInfo personInfo,
        @WebParam(name = "score", targetNamespace = "http://tempuri.org/")
        int score);

    /**
     * 
     * @param cameraId
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "HasExistClientsQuestRealVideoStream", action = "http://tempuri.org/IWebService/HasExistClientsQuestRealVideoStream")
    @WebResult(name = "HasExistClientsQuestRealVideoStreamResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HasExistClientsQuestRealVideoStream", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HasExistClientsQuestRealVideoStream")
    @ResponseWrapper(localName = "HasExistClientsQuestRealVideoStreamResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HasExistClientsQuestRealVideoStreamResponse")
    public boolean hasExistClientsQuestRealVideoStream(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId);

    /**
     * 
     * @param cameraId
     * @param jpegFrameBytes
     * @param time
     * @param token
     */
    @WebMethod(operationName = "UpRealVideoStream", action = "http://tempuri.org/IWebService/UpRealVideoStream")
    @RequestWrapper(localName = "UpRealVideoStream", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpRealVideoStream")
    @ResponseWrapper(localName = "UpRealVideoStreamResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpRealVideoStreamResponse")
    public void upRealVideoStream(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "time", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar time,
        @WebParam(name = "jpegFrameBytes", targetNamespace = "http://tempuri.org/")
        byte[] jpegFrameBytes);

    /**
     * 
     * @param detectPort
     * @param jpegFrameBytes
     * @param detectServerIp
     * @return
     *     returns org.tempuri.ArrayOfObjectDetectInfo
     */
    @WebMethod(operationName = "DetectObjects", action = "http://tempuri.org/IWebService/DetectObjects")
    @WebResult(name = "DetectObjectsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DetectObjects", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DetectObjects")
    @ResponseWrapper(localName = "DetectObjectsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DetectObjectsResponse")
    public ArrayOfObjectDetectInfo detectObjects(
        @WebParam(name = "jpegFrameBytes", targetNamespace = "http://tempuri.org/")
        byte[] jpegFrameBytes,
        @WebParam(name = "detectServerIp", targetNamespace = "http://tempuri.org/")
        String detectServerIp,
        @WebParam(name = "detectPort", targetNamespace = "http://tempuri.org/")
        int detectPort);

    /**
     * 
     * @param cameraId
     * @return
     *     returns org.tempuri.ArrayOfPersonKeyInfo
     */
    @WebMethod(operationName = "GetPersonKeyInfoListByCameraID", action = "http://tempuri.org/IWebService/GetPersonKeyInfoListByCameraID")
    @WebResult(name = "GetPersonKeyInfoListByCameraIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonKeyInfoListByCameraID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonKeyInfoListByCameraID")
    @ResponseWrapper(localName = "GetPersonKeyInfoListByCameraIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonKeyInfoListByCameraIDResponse")
    public ArrayOfPersonKeyInfo getPersonKeyInfoListByCameraID(
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId);

    /**
     * 
     * @param uid
     * @param pwd
     * @return
     *     returns long
     */
    @WebMethod(operationName = "VipPersonLogin", action = "http://tempuri.org/IWebService/VipPersonLogin")
    @WebResult(name = "VipPersonLoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VipPersonLogin", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VipPersonLogin")
    @ResponseWrapper(localName = "VipPersonLoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VipPersonLoginResponse")
    public long vipPersonLogin(
        @WebParam(name = "uid", targetNamespace = "http://tempuri.org/")
        String uid,
        @WebParam(name = "pwd", targetNamespace = "http://tempuri.org/")
        String pwd);

    /**
     * 
     * @param personID
     * @return
     *     returns org.tempuri.ArrayOfVisitorInfo
     */
    @WebMethod(operationName = "GetVisitorInfoListByCreateVipPersonID", action = "http://tempuri.org/IWebService/GetVisitorInfoListByCreateVipPersonID")
    @WebResult(name = "GetVisitorInfoListByCreateVipPersonIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetVisitorInfoListByCreateVipPersonID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVisitorInfoListByCreateVipPersonID")
    @ResponseWrapper(localName = "GetVisitorInfoListByCreateVipPersonIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVisitorInfoListByCreateVipPersonIDResponse")
    public ArrayOfVisitorInfo getVisitorInfoListByCreateVipPersonID(
        @WebParam(name = "personID", targetNamespace = "http://tempuri.org/")
        long personID);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetGlobalPersonLastUpdateFlag", action = "http://tempuri.org/IWebService/GetGlobalPersonLastUpdateFlag")
    @WebResult(name = "GetGlobalPersonLastUpdateFlagResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetGlobalPersonLastUpdateFlag", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGlobalPersonLastUpdateFlag")
    @ResponseWrapper(localName = "GetGlobalPersonLastUpdateFlagResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetGlobalPersonLastUpdateFlagResponse")
    public String getGlobalPersonLastUpdateFlag();

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetCurDateTime", action = "http://tempuri.org/IWebService/GetCurDateTime")
    @WebResult(name = "GetCurDateTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCurDateTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurDateTime")
    @ResponseWrapper(localName = "GetCurDateTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCurDateTimeResponse")
    public XMLGregorianCalendar getCurDateTime();

    /**
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetXmlSystemConfigure", action = "http://tempuri.org/IWebService/GetXmlSystemConfigure")
    @WebResult(name = "GetXmlSystemConfigureResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetXmlSystemConfigure", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetXmlSystemConfigure")
    @ResponseWrapper(localName = "GetXmlSystemConfigureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetXmlSystemConfigureResponse")
    public String getXmlSystemConfigure(
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        String key);

    /**
     * 
     * @param dateTime
     * @param score
     * @param takeFaceBytes
     * @param cameraId
     * @param text
     * @param token
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AddRecoFailureRecordToDb", action = "http://tempuri.org/IWebService/AddRecoFailureRecordToDb")
    @WebResult(name = "AddRecoFailureRecordToDbResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddRecoFailureRecordToDb", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRecoFailureRecordToDb")
    @ResponseWrapper(localName = "AddRecoFailureRecordToDbResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddRecoFailureRecordToDbResponse")
    public boolean addRecoFailureRecordToDb(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId,
        @WebParam(name = "dateTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar dateTime,
        @WebParam(name = "takeFaceBytes", targetNamespace = "http://tempuri.org/")
        byte[] takeFaceBytes,
        @WebParam(name = "text", targetNamespace = "http://tempuri.org/")
        String text,
        @WebParam(name = "score", targetNamespace = "http://tempuri.org/")
        int score);

    /**
     * 
     * @param cameraId
     * @param token
     * @return
     *     returns org.tempuri.OpenDoorMode
     */
    @WebMethod(operationName = "GetDoorActionCode", action = "http://tempuri.org/IWebService/GetDoorActionCode")
    @WebResult(name = "GetDoorActionCodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDoorActionCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDoorActionCode")
    @ResponseWrapper(localName = "GetDoorActionCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDoorActionCodeResponse")
    public OpenDoorMode getDoorActionCode(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "cameraId", targetNamespace = "http://tempuri.org/")
        int cameraId);

}
