/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaNationInterFace */

#ifndef _Included_JavaNationInterFace
#define _Included_JavaNationInterFace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaNationInterFace
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaNationInterFace_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
